# Generated by Django 5.0.6 on 2024-07-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('job_desc', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('res', models.TextField(blank=True)),
                ('require', models.TextField(blank=True)),
                ('skills', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('company_desc', models.TextField(blank=True)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('contactPhone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
