# Generated by Django 5.0.6 on 2024-07-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='contactEmail',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='contactPhone',
            new_name='contact_phone',
        ),
    ]
