# Generated by Django 5.0.6 on 2024-07-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_userotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userotp',
            options={'ordering': ['-created_at']},
        ),
    ]
