services:
  - type: web
    name: jobs-network
    env: python
    plan: free
    buildCommand:
      - pip install -r requirements.txt
      - python manage.py collectstatic --noinput
      - python manage.py migrate
    startCommand: cd server && gunicorn server.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: SECRET_KEY
        sync: false
        value: ${SECRET_KEY}
      - key: EMAIL_ID
        sync: false
        value: ${EMAIL_ID}
      - key: EMAIL_PASSWORD
        sync: false
        value: ${EMAIL_PASSWORD}

cronJobs:
  - name: keep-alive
    schedule: "*/14 * * * *"
    command: "curl -I https://jobs-network.onrender.com && echo hello"
