services:
  - type: web
    name: jobs-network
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd server && gunicorn server.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: EMAIL_ID
        value: ${EMAIL_ID}
      - key: EMAIL_PASSWORD
        value: ${EMAIL_PASSWORD}
